language: node_js
node_js:
  - 0.10

notifications:
  email: false

before_install:
  - npm install -g grunt-cli
  - grunt install_deps

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 1 # give server time to start

script:
  - grunt test
